[build]
  command = "npm run build"
  publish = ".next"

[template]
  incoming-hooks = ["WixEvents"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = "tu_cliente_id_de_wix"
  WIX_REFRESH_TOKEN = "tu_refresh_token_de_wix"